// <auto-generated />

using Intersect.Server.Database.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Intersect.Server.Migrations.MySql.Logging
{
    [DbContext(typeof(MySqlLoggingContext))]
    [Migration("20191118024649_RequestLogs")]
    partial class RequestLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Intersect.Server.Database.Logging.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Level");

                    b.Property<string>("Method");

                    b.Property<string>("SerializedRequestHeaders")
                        .HasColumnName("RequestHeaders");

                    b.Property<string>("SerializedResponseHeaders")
                        .HasColumnName("ResponseHeaders");

                    b.Property<int>("StatusCode");

                    b.Property<string>("StatusMessage");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Uri");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
