blank_issues_enabled: false
contact_links:
  - name: Ascension Game Dev
    url: https://ascensiongamedev.com
    about: Please ask and answer questions on our public forum.
  - name: Community Discord
    url: https://discord.gg/Ggt3KJV
    about: Feel free to chat or also find support in our Discord community.
