// <auto-generated />
using Intersect.Server.Classes.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Intersect.Server.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    [Migration("20180307035259_GameData")]
    partial class GameData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Intersect.GameObjects.AnimationBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DisableLowerRotations");

                    b.Property<bool>("DisableUpperRotations");

                    b.Property<int>("Lower.FrameCount");

                    b.Property<int>("Lower.FrameSpeed");

                    b.Property<int>("Lower.LoopCount");

                    b.Property<string>("Lower.Sprite");

                    b.Property<int>("Lower.XFrames");

                    b.Property<int>("Lower.YFrames");

                    b.Property<string>("Name");

                    b.Property<string>("Sound");

                    b.Property<int>("Upper.FrameCount");

                    b.Property<int>("Upper.FrameSpeed");

                    b.Property<int>("Upper.LoopCount");

                    b.Property<string>("Upper.Sprite");

                    b.Property<int>("Upper.XFrames");

                    b.Property<int>("Upper.YFrames");

                    b.HasKey("Id");

                    b.ToTable("Animations");
                });
#pragma warning restore 612, 618
        }
    }
}
