//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Sockets;

namespace Intersect_Server.Classes
{
	public class Client
	{
		public int clientIndex;
		public int entityIndex;
		public bool isConnected;
		private List<byte> myBuffer = new List<byte> ();
		public string myName = "";
		public long connectionTimeout;
		public long timeoutLength = 10;
		public long pingTime = 0;
		public bool isEditor;
        public string packets = "";
        public int power = 0;
        public int id = -1;
        private byte[] readBuff = new byte[1];
        public long connectTime;
        public TcpClient mySocket;
        public NetworkStream myStream;
        private PacketHandler packetHandler = new PacketHandler();


        public Client(int myIndex, int entIndex, TcpClient  socket)
		{
            mySocket = socket;
            mySocket.SendBufferSize = 4096;
            mySocket.ReceiveBufferSize = 4096;
            myStream = mySocket.GetStream();
            readBuff = new byte[mySocket.ReceiveBufferSize];
            connectTime = Environment.TickCount;
            myStream.BeginRead(readBuff, 0, mySocket.ReceiveBufferSize, OnReceiveData, connectTime);
			clientIndex = myIndex;
			entityIndex = entIndex;
			PacketSender.SendPing (this);
			isConnected = true;
			connectionTimeout = -1;

		}

        private void OnReceiveData(IAsyncResult ar)
        {
            ByteBuffer buff;
            int packetLen;
            var newBytes = new byte[1];
            if ((long)ar.AsyncState != connectTime) { return; }
            try
            {
                var readbytes = myStream.EndRead(ar);
                if (readbytes <= 0) { Console.WriteLine("No bytes read, disconnecting."); HandleDisconnect(); return; }
                newBytes = new byte[readbytes];
                Buffer.BlockCopy(readBuff, 0, newBytes, 0, readbytes);
                myBuffer.AddRange(newBytes);
                if (myBuffer.Count >= 4)
                {
                    buff = new ByteBuffer();
                    buff.WriteBytes(myBuffer.ToArray());
                    while (buff.Length() >= 4)
                    {
                        packetLen = buff.ReadInteger(false);
                        if (packetLen == 0)
                        {
                            break;
                        }
                        if (buff.Length() >= packetLen + 4)
                        {
                            buff.ReadInteger();
                            packetHandler.HandlePacket(this, buff.ReadBytes(packetLen));
                        }
                        else
                        {
                            break;
                        }
                    }
                    myBuffer.Clear();
                    if (buff.Length() > 0)
                    {
                        myBuffer.AddRange(buff.ReadBytes(buff.Length()));
                    }
                }
                readBuff = new byte[mySocket.ReceiveBufferSize];
                myStream.BeginRead(readBuff, 0, mySocket.ReceiveBufferSize, OnReceiveData, connectTime);
            }
            catch (Exception)
            {
                Console.WriteLine("Socket end read error.");
                HandleDisconnect(); 
                return;
            }
        }

		public void HandleDisconnect ()
		{
            if (isConnected)
            {
                isConnected = false;
                if (myStream != null) { myStream.Close(); }
                myStream = null;
                if (mySocket != null) { mySocket.Close(); }
                mySocket = null;
                try
                {
                    Console.WriteLine("Client disconnected.");
                    if (entityIndex > -1)
                    {
                        Database.SavePlayer(Globals.Clients[clientIndex]);
                        PacketSender.SendEntityLeave(entityIndex,0);
                        if (Globals.Entities[entityIndex] == null) { return; }
                        PacketSender.SendGlobalMsg(Globals.Entities[entityIndex].MyName + " has left the Intersect engine");
                        Globals.Clients[clientIndex] = null;
                        Globals.Entities[entityIndex] = null;

                    }
                }
                catch (Exception) { }
            }
			isConnected = false;
		}

		public void Update (PacketHandler packetHandler)
		{
			int readAmt;

			var tempBuff = new byte[4096];

			do {
				try {
					if (IsConnected(mySocket)) {
						if (connectionTimeout > -1 && connectionTimeout < Environment.TickCount) {
							//Disconnect
							HandleDisconnect ();
							return;
						} else {
							if (pingTime < Environment.TickCount) {
								PacketSender.SendPing (this);
							}
						}
						readAmt = myStream.Read (tempBuff, 0, 4096);
						if (readAmt > 0) {
							for (var i = 0; i < readAmt; i++) {
								myBuffer.Add (tempBuff [i]);
							}
						} else {
							HandleDisconnect ();
							return;
						}
					} else {
						HandleDisconnect ();
						return;
					}
				} catch {
					HandleDisconnect ();
					return;
				}
				
			} while (true);
		}

        public void HandleData(byte[] packet)
        {
            ByteBuffer buff;
			int packetLen;
            myBuffer.AddRange(packet);
            if (myBuffer.Count >= 4)
            {
                buff = new ByteBuffer();
                buff.WriteBytes(myBuffer.ToArray());
                while (buff.Length() >= 4)
                {
                    packetLen = buff.ReadInteger(false);
                    if (packetLen == 0)
                    {
                        break;
                    }
                    if (buff.Length() >= packetLen)
                    {
                        buff.ReadInteger();
                        packetHandler.HandlePacket(this, buff.ReadBytes(packetLen));
                    }
                    else
                    {
                        break;
                    }
                }
                myBuffer.Clear();
                if (buff.Length() > 0)
                {
                    myBuffer.AddRange(buff.ReadBytes(buff.Length()));
                }
            }
        }

		private void HandlePacket (byte[] packet)
		{
			var buff = new ByteBuffer ();
			buff.WriteBytes (packet);
			var tempStr = buff.ReadString ();
			Console.WriteLine (tempStr);
			SendPacket (packet);
			buff.Dispose ();
		}

		public void SendPacket (byte[] packet)
		{
		    var buff = new ByteBuffer ();
			try {
				if (isConnected) {
					buff.WriteInteger (packet.Length);
					buff.WriteBytes (packet);
                    myStream.Write(buff.ToArray(), 0, buff.Count());
				}
			} catch (Exception ex) {
                Console.WriteLine("Send exception, disconnecting.");
                Console.WriteLine(ex.InnerException);
                Console.WriteLine(ex.ToString());
                HandleDisconnect();
                return;
			}
		}

		public static bool IsConnected (TcpClient socket)
		{
            return socket.Connected;
		}
	}
}

