//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect.Framework.Reflection {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReflectionStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReflectionStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Intersect.Framework.Reflection.ReflectionStrings", typeof(ReflectionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnpackEmbeddedFile_MissingManifestResourceInfo {
            get {
                return ResourceManager.GetString("UnpackEmbeddedFile_MissingManifestResourceInfo", resourceCulture);
            }
        }
        
        internal static string UnpackEmbeddedFile_UnableToOpenStream {
            get {
                return ResourceManager.GetString("UnpackEmbeddedFile_UnableToOpenStream", resourceCulture);
            }
        }
        
        internal static string ExpectedAnIncompleteTypeButReceivedX {
            get {
                return ResourceManager.GetString("ExpectedAnIncompleteTypeButReceivedX", resourceCulture);
            }
        }
        
        internal static string TypeExtensions_FindGenericTypeParameters_NotGeneric {
            get {
                return ResourceManager.GetString("TypeExtensions_FindGenericTypeParameters_NotGeneric", resourceCulture);
            }
        }
        
        internal static string TypeExtensions_FindGenericTypeParameters_NotValidGenericTypeDefinition {
            get {
                return ResourceManager.GetString("TypeExtensions_FindGenericTypeParameters_NotValidGenericTypeDefinition", resourceCulture);
            }
        }
        
        internal static string TypeExtensions_FindConcreteType_ExpectedAbstractOrInterface {
            get {
                return ResourceManager.GetString("TypeExtensions_FindConcreteType_ExpectedAbstractOrInterface", resourceCulture);
            }
        }
        
        internal static string AssemblyExtensions_NoMatchingSubtype {
            get {
                return ResourceManager.GetString("AssemblyExtensions_NoMatchingSubtype", resourceCulture);
            }
        }
        
        internal static string AssemblyExtensions_FailedToCreateInstance {
            get {
                return ResourceManager.GetString("AssemblyExtensions_FailedToCreateInstance", resourceCulture);
            }
        }
    }
}
