//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect_Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intersect_Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Strings&gt;
        ///	&lt;Main&gt;
        ///		&lt;string id=&quot;title&quot;&gt;{00}&lt;/String&gt;
        ///	&lt;/Main&gt;
        ///&lt;/Strings&gt;.
        /// </summary>
        internal static string Client_English {
            get {
                return ResourceManager.GetString("Client_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Strings&gt;
        ///	&lt;Main&gt;
        ///		&lt;string id=&quot;title&quot;&gt;{00}&lt;/string&gt;
        ///	&lt;/Main&gt;
        ///&lt;/Strings&gt;.
        /// </summary>
        internal static string Editor_English {
            get {
                return ResourceManager.GetString("Editor_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Strings&gt;
        ///	&lt;Main&gt;
        ///		&lt;string id=&quot;title&quot;&gt;Intersect Migration Tool&lt;/string&gt;
        ///		&lt;string id=&quot;tagline&quot;&gt;                          free 2d orpg engine&lt;/string&gt;
        ///		&lt;string id=&quot;version&quot;&gt;Version {00}&lt;/string&gt;
        ///		&lt;string id=&quot;exit&quot;&gt;Press any key to exit.&lt;/string&gt;
        ///	&lt;/Main&gt;
        ///	&lt;Intro&gt;
        ///		&lt;string id=&quot;support&quot;&gt;For help, support, and updates visit: http://ascensiongamedev.com&lt;/string&gt;
        ///		&lt;string id=&quot;purpose&quot;&gt;Use this to update your database when deploying the versions of Intersect.&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Migrator_English {
            get {
                return ResourceManager.GetString("Migrator_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Strings&gt;
        ///	&lt;Main&gt;
        ///		&lt;string id=&quot;title&quot;&gt;{00}&lt;/string&gt;
        ///	&lt;/Main&gt;
        ///&lt;/Strings&gt;.
        /// </summary>
        internal static string Server_English {
            get {
                return ResourceManager.GetString("Server_English", resourceCulture);
            }
        }
    }
}
