//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect.Framework.Core.Config {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptionsStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Intersect.Framework.Core.Config.OptionsStrings", typeof(OptionsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Category_General {
            get {
                return ResourceManager.GetString("Category_General", resourceCulture);
            }
        }
        
        internal static string Category_Logging {
            get {
                return ResourceManager.GetString("Category_Logging", resourceCulture);
            }
        }
        
        internal static string Category_Metrics {
            get {
                return ResourceManager.GetString("Category_Metrics", resourceCulture);
            }
        }
        
        internal static string Category_GameDatabase {
            get {
                return ResourceManager.GetString("Category_GameDatabase", resourceCulture);
            }
        }
        
        internal static string Category_LoggingDatabase {
            get {
                return ResourceManager.GetString("Category_LoggingDatabase", resourceCulture);
            }
        }
        
        internal static string Category_PlayerDatabase {
            get {
                return ResourceManager.GetString("Category_PlayerDatabase", resourceCulture);
            }
        }
        
        internal static string Category_Security {
            get {
                return ResourceManager.GetString("Category_Security", resourceCulture);
            }
        }
        
        internal static string Category_SmtpSettings {
            get {
                return ResourceManager.GetString("Category_SmtpSettings", resourceCulture);
            }
        }
        
        internal static string Category_Chat {
            get {
                return ResourceManager.GetString("Category_Chat", resourceCulture);
            }
        }
        
        internal static string Category_Packets {
            get {
                return ResourceManager.GetString("Category_Packets", resourceCulture);
            }
        }
    }
}
