// <auto-generated />
using System;
using Intersect.Server.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.MySql.Game
{
    [DbContext(typeof(MySqlGameContext))]
    [Migration("20220810231626_DropLegacyFolder")]
    partial class DropLegacyFolder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Intersect.GameObjects.AnimationBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<bool>("CompleteSound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("Sound")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Animations");
                });

            modelBuilder.Entity("Intersect.GameObjects.ClassBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AttackAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("AttackAnimation");

                    b.Property<int>("AttackSpeedModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackSpeedValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CritChance")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CritMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpIncrease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpOverridesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExperienceOverrides");

                    b.Property<bool>("IncreasePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonBaseStats")
                        .HasColumnType("TEXT")
                        .HasColumnName("BaseStats");

                    b.Property<string>("JsonBaseVitals")
                        .HasColumnType("TEXT")
                        .HasColumnName("BaseVitals");

                    b.Property<string>("JsonItems")
                        .HasColumnType("TEXT")
                        .HasColumnName("Items");

                    b.Property<string>("JsonSpells")
                        .HasColumnType("TEXT")
                        .HasColumnName("Spells");

                    b.Property<string>("JsonSprites")
                        .HasColumnType("TEXT")
                        .HasColumnName("Sprites");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<int>("PointIncrease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegenJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalRegen");

                    b.Property<int>("Scaling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScalingStat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpawnDir")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpawnMapId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("SpawnMap");

                    b.Property<int>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatIncreaseJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("StatIncreases");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VitalIncreaseJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalIncreases");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Intersect.GameObjects.Crafting.CraftBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Event");

                    b.Property<int>("FailureChance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ingredients");

                    b.Property<byte[]>("ItemId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ItemLossChance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Crafts");
                });

            modelBuilder.Entity("Intersect.GameObjects.CraftingTableBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("CraftsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Crafts");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CraftingTables");
                });

            modelBuilder.Entity("Intersect.GameObjects.Events.EventBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<bool>("CommonEvent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Global")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MapId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("PagesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Pages");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<int>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Intersect.GameObjects.GuildVariableBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("TextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("GuildVariables");
                });

            modelBuilder.Entity("Intersect.GameObjects.ItemBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Animation");

                    b.Property<byte[]>("AttackAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("AttackAnimation");

                    b.Property<int>("AttackSpeedModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackSpeedValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockAbsorption")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockChance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDrop")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Bound");

                    b.Property<bool>("CanGuildBank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSell")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanTrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CannotUseMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CooldownGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("CritChance")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CritMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DropChanceOnDeath")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EquipmentAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("EquipmentAnimation");

                    b.Property<int>("EquipmentSlot")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Event");

                    b.Property<string>("FemalePaperdoll")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreCooldownReduction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreGlobalCooldown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("Color");

                    b.Property<string>("JsonUsageRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("UsageRequirements");

                    b.Property<string>("MalePaperdoll")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBankStack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxInventoryStack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("PercentageStatsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PercentageStatsGiven");

                    b.Property<string>("PercentageVitalsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PercentageVitalsGiven");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProjectileId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Projectile");

                    b.Property<bool>("QuickCast")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scaling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScalingStat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SingleUse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DestroySpell");

                    b.Property<int>("SlotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpellId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Spell");

                    b.Property<bool>("Stackable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatGrowth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("StatsGiven");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoHanded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VitalsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalsGiven");

                    b.Property<string>("VitalsRegenJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalsRegen");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Intersect.GameObjects.NpcBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<bool>("Aggressive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttackAllies")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AttackAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("AttackAnimation");

                    b.Property<string>("AttackOnSightConditionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("AttackOnSightConditions");

                    b.Property<int>("AttackSpeedModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackSpeedValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CraftsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Spells");

                    b.Property<int>("CritChance")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CritMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FleeHealthPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FocusHighestDamageDealer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImmunitiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Immunities");

                    b.Property<bool>("IndividualizedLoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonAggroList")
                        .HasColumnType("TEXT")
                        .HasColumnName("AggroList");

                    b.Property<string>("JsonColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("Color");

                    b.Property<string>("JsonDrops")
                        .HasColumnType("TEXT")
                        .HasColumnName("Drops");

                    b.Property<string>("JsonMaxVital")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaxVital");

                    b.Property<string>("JsonStat")
                        .HasColumnType("TEXT")
                        .HasColumnName("Stats");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Movement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("NpcVsNpcEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("OnDeathEventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("OnDeathEvent");

                    b.Property<byte[]>("OnDeathPartyEventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("OnDeathPartyEvent");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("PlayerCanAttackConditionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PlayerCanAttackConditions");

                    b.Property<string>("PlayerFriendConditionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PlayerFriendConditions");

                    b.Property<string>("RegenJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalRegen");

                    b.Property<int>("ResetRadius")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scaling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScalingStat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SightRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpawnDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sprite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Swarm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tenacity")
                        .HasColumnType("REAL");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("Intersect.GameObjects.PlayerVariableBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("TextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PlayerVariables");
                });

            modelBuilder.Entity("Intersect.GameObjects.ProjectileBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AmmoItemId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Ammo");

                    b.Property<int>("AmmoRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Animations");

                    b.Property<int>("Delay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GrappleHook")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrappleHookOptionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("GrappleHookOptions");

                    b.Property<bool>("IgnoreActiveResources")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreExhaustedResources")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreMapBlocks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreZDimension")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Knockback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<bool>("PierceTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpawnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("SpawnLocations");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpellId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Spell");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Projectiles");
                });

            modelBuilder.Entity("Intersect.GameObjects.QuestBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("BeforeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedCategory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DoNotShowUnlessRequirementsMet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDescription")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EndEventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("EndEvent");

                    b.Property<string>("InProgressCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("InProgressDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("Requirements");

                    b.Property<bool>("LogAfterComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LogBeforeOffer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("OrderValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<bool>("Quitable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Repeatable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDescription")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("StartEventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("StartEvent");

                    b.Property<string>("TasksJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tasks");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnstartedCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Intersect.GameObjects.ResourceBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Animation");

                    b.Property<string>("CannotHarvestMessage")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Event");

                    b.Property<string>("JsonDrops")
                        .HasColumnType("TEXT")
                        .HasColumnName("Drops");

                    b.Property<string>("JsonHarvestingRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("HarvestingRequirements");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<int>("SpawnDuration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tool")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitalRegen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WalkableAfter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WalkableBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Intersect.GameObjects.ServerVariableBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("TextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ServerVariables");
                });

            modelBuilder.Entity("Intersect.GameObjects.ShopBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("BuySound")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BuyingWhitelist")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DefaultCurrencyId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("DefaultCurrency");

                    b.Property<string>("JsonBuyingItems")
                        .HasColumnType("TEXT")
                        .HasColumnName("BuyingItems");

                    b.Property<string>("JsonSellingItems")
                        .HasColumnType("TEXT")
                        .HasColumnName("SellingItems");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("SellSound")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Intersect.GameObjects.SpellBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<bool>("Bound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CannotCastMessage")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CastAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("CastAnimation");

                    b.Property<int>("CastDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CooldownGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EventId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Event");

                    b.Property<byte[]>("HitAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("HitAnimation");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreCooldownReduction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreGlobalCooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonCastRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("CastRequirements");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<int>("SpellType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TickAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("TickAnimation");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VitalCostJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("VitalCost");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Intersect.GameObjects.TilesetBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Tilesets");
                });

            modelBuilder.Entity("Intersect.GameObjects.TimeBase", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("DaylightHuesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("DaylightHues");

                    b.Property<int>("RangeInterval")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL");

                    b.Property<bool>("SyncTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("Intersect.Models.ContentString", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentStrings");
                });

            modelBuilder.Entity("Intersect.Models.Folder", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(0);

                    b.Property<int>("DescriptorType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<byte[]>("NameId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnOrder(2);

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Intersect.Models.LocaleContentString", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Locale");

                    b.ToTable("LocaleContentStrings");
                });

            modelBuilder.Entity("Intersect.Server.Maps.MapController", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("AHue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AttributeData")
                        .HasColumnType("BLOB")
                        .HasColumnName("Attributes");

                    b.Property<int>("BHue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Down")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("EventIdsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Events");

                    b.Property<string>("Fog")
                        .HasColumnType("TEXT");

                    b.Property<int>("FogTransparency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FogXSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FogYSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GHue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideEquipment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndoors")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Left")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("LightsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Lights");

                    b.Property<string>("Music")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("NpcSpawnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("NpcSpawns");

                    b.Property<string>("OverlayGraphic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panorama")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("BLOB")
                        .HasColumnOrder(1);

                    b.Property<string>("PlayerLightColorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PlayerLightColor");

                    b.Property<float>("PlayerLightExpand")
                        .HasColumnType("REAL");

                    b.Property<byte>("PlayerLightIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerLightSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RHue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Right")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Sound")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TileData")
                        .HasColumnType("BLOB");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Up")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("WeatherAnimationId")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("WeatherAnimation");

                    b.Property<int>("WeatherIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeatherXSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeatherYSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Intersect.GameObjects.AnimationBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Intersect.GameObjects.AnimationLayer", "Lower", b1 =>
                        {
                            b1.Property<byte[]>("AnimationBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<bool>("AlternateRenderLayer")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("DisableRotations")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FrameSpeed")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Light")
                                .HasColumnType("TEXT");

                            b1.Property<int>("LoopCount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Sprite")
                                .HasColumnType("TEXT");

                            b1.Property<int>("XFrames")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("YFrames")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AnimationBaseId");

                            b1.ToTable("Animations");

                            b1.WithOwner()
                                .HasForeignKey("AnimationBaseId");
                        });

                    b.OwnsOne("Intersect.GameObjects.AnimationLayer", "Upper", b1 =>
                        {
                            b1.Property<byte[]>("AnimationBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<bool>("AlternateRenderLayer")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("DisableRotations")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FrameSpeed")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Light")
                                .HasColumnType("TEXT");

                            b1.Property<int>("LoopCount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Sprite")
                                .HasColumnType("TEXT");

                            b1.Property<int>("XFrames")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("YFrames")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AnimationBaseId");

                            b1.ToTable("Animations");

                            b1.WithOwner()
                                .HasForeignKey("AnimationBaseId");
                        });

                    b.Navigation("Lower");

                    b.Navigation("Parent");

                    b.Navigation("Upper");
                });

            modelBuilder.Entity("Intersect.GameObjects.ClassBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.Crafting.CraftBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.CraftingTableBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.Events.EventBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.GuildVariableBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.ItemBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Intersect.GameObjects.ConsumableData", "Consumable", b1 =>
                        {
                            b1.Property<byte[]>("ItemBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<int>("Percentage")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemBaseId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemBaseId");
                        });

                    b.OwnsOne("Intersect.GameObjects.EffectData", "Effect", b1 =>
                        {
                            b1.Property<byte[]>("ItemBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<int>("Percentage")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemBaseId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemBaseId");
                        });

                    b.Navigation("Consumable");

                    b.Navigation("Effect");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.NpcBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.PlayerVariableBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.ProjectileBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.QuestBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.ResourceBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Intersect.GameObjects.ResourceState", "Exhausted", b1 =>
                        {
                            b1.Property<byte[]>("ResourceBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<string>("Graphic")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("GraphicFromTileset")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RenderBelowEntities")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResourceBaseId");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceBaseId");
                        });

                    b.OwnsOne("Intersect.GameObjects.ResourceState", "Initial", b1 =>
                        {
                            b1.Property<byte[]>("ResourceBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<string>("Graphic")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("GraphicFromTileset")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RenderBelowEntities")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResourceBaseId");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceBaseId");
                        });

                    b.Navigation("Exhausted");

                    b.Navigation("Initial");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.ServerVariableBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.ShopBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.GameObjects.SpellBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Intersect.GameObjects.SpellCombatData", "Combat", b1 =>
                        {
                            b1.Property<byte[]>("SpellBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<int>("CastRange")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CritChance")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("REAL");

                            b1.Property<int>("DamageType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Duration")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Effect")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Friendly")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HitRadius")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HoTDoT")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HotDotInterval")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OnHitDuration")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OnHit");

                            b1.Property<string>("PercentageStatDiffJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("PercentageStatDiff");

                            b1.Property<byte[]>("ProjectileId")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Projectile");

                            b1.Property<int>("Scaling")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ScalingStat")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StatDiffJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("StatDiff");

                            b1.Property<int>("TargetType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("TransformSprite")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TrapDuration")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Trap");

                            b1.Property<string>("VitalDiffJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("VitalDiff");

                            b1.HasKey("SpellBaseId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellBaseId");
                        });

                    b.OwnsOne("Intersect.GameObjects.SpellDashOpts", "Dash", b1 =>
                        {
                            b1.Property<byte[]>("SpellBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<bool>("IgnoreActiveResources")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IgnoreInactiveResources")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IgnoreMapBlocks")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IgnoreZDimensionAttributes")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SpellBaseId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellBaseId");
                        });

                    b.OwnsOne("Intersect.GameObjects.SpellWarpData", "Warp", b1 =>
                        {
                            b1.Property<byte[]>("SpellBaseId")
                                .HasColumnType("BLOB");

                            b1.Property<int>("Dir")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("MapId")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SpellBaseId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellBaseId");
                        });

                    b.Navigation("Combat");

                    b.Navigation("Dash");

                    b.Navigation("Parent");

                    b.Navigation("Warp");
                });

            modelBuilder.Entity("Intersect.GameObjects.TilesetBase", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.Models.Folder", b =>
                {
                    b.HasOne("Intersect.Models.ContentString", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Name");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.Models.LocaleContentString", b =>
                {
                    b.HasOne("Intersect.Models.ContentString", "ContentString")
                        .WithMany("Localizations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentString");
                });

            modelBuilder.Entity("Intersect.Server.Maps.MapController", b =>
                {
                    b.HasOne("Intersect.Models.Folder", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Intersect.Models.ContentString", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("Intersect.Models.Folder", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
