// <auto-generated />
using Intersect.Server.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.MySql.Game
{
    [DbContext(typeof(MySqlGameContext))]
    [Migration("20251210000000_AddGrievousWoundsAndHealBoost")]
    partial class AddGrievousWoundsAndHealBoost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Intersect.Framework.Core.GameObjects.Spells.SpellDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Combat_KnockbackTiles")
                        .HasColumnType("int");

                    b.Property<int>("Combat_GrievousWoundsReduction")
                        .HasColumnType("int");

                    b.Property<int>("Combat_HealingBoostPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
