name: request-help

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

env:
  VERSION_PREFIX: ${{ github.event.issue.number }}
  VERSION_SUFFIX: -pr-test

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/helptest')}}
    steps:

    - name: Check comment body
      run: echo ${{ github.event.comment.body }}

    - name: Checkout pull request
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
        submodules: recursive

    - name: Cache binaries
      uses: actions/cache@v3
      id: cache-binaries
      with:
        key: ${{ runner.os }}-binaries-${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}-${{ hashFiles('Intersect*/**/*.cs*') }}
        path: |
          Intersect*/bin/Release/**/*

    - name: Setup dotnet
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Cache NuGet dependencies
      uses: actions/cache@v3
      id: cache-nuget
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      with:
        key: ${{ runner.os }}-nuget-${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}-${{ hashFiles('Intersect*/*.csproj') }}
        path: |
          ~/.nuget/packages
          Intersect*/obj/

    - name: Restore NuGet Packages
      if: steps.cache-binaries.outputs.cache-hit != 'true' && steps.cache-nuget.outputs.cache-hit != 'true'
      run: dotnet restore Intersect.sln

    # - run: ls -R ~/.nuget/packages

    - name: Build solution
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      run: |
        dotnet publish Intersect.sln -r win-x64   -p:Configuration=Release -p:PackageVersion=${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}.${{ github.run_number }}+build.${{ github.sha }} -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }}
        git apply disable-windows-editor.patch
        dotnet publish Intersect.sln -r linux-x64 -p:Configuration=Release -p:PackageVersion=${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}.${{ github.run_number }}+build.${{ github.sha }} -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }}
        dotnet publish Intersect.sln -r osx-x64   -p:Configuration=Release -p:PackageVersion=${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}.${{ github.run_number }}+build.${{ github.sha }} -p:Version=${{ env.VERSION_PREFIX }}.${{ github.run_number }}

    - name: Package artifacts
      uses: AscensionGameDev/actions@cc2eb0e356546042e4dc7eca6788fd0b5a063b32
      with:
        bundle: .github/bundles/patch.json
        version: ${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}.${{ github.run_number }}+build.${{ github.sha }}

    - name: Extract archive to avoid zips inside of zips
      run: 7z x dist/**/*.zip

    - name: Delete inner zip
      run: del dist/**/*.zip

    - name: Upload artifacts for workflow debugging
      uses: actions/upload-artifact@v3
      with:
        name: intersect-pr${{ env.VERSION_PREFIX }}-test${{ github.run_number }}+build.${{ github.sha }}
        path: "dist/patch/*.zip"

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}
        body: |
            Developers have requested community assistance to test the code changes in this pull request.

            If you'd like to help you can download binaries for this PR [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            These builds are only meant for testing to validate bug fixes and could cause significant damage to your game data. In other words, make a backup of your game data before proceeding.

            Please comment below to provide testing feedback. Thanks!

    - name: Delete comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}
        script: |
            github.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.comment.id }},
            })

